version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ./dist:/app/dist
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318

  webserver:
      build:
        context: .
        dockerfile: nginx.Dockerfile
      volumes:
        - ./dist:/usr/share/nginx/html
        - ./nginx/templates:/etc/nginx/templates
      ports:
        - "8080:80"
      environment:
        - OTLP_COLLECTOR_ENDPOINT=http://jaeger:4318
        - APP_DOMAIN=localhost
      depends_on:
        app:
          condition: service_completed_successfully